name: taiko

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install
        run: npm install
      - name: install browser dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libwoff1 \
                        libopus0 \
                        libwebp6 \
                        libwebpdemux2 \
                        libenchant1c2a \
                        libgudev-1.0-0 \
                        libsecret-1-0 \
                        libhyphen0 \
                        libgdk-pixbuf2.0-0 \
                        libegl1 \
                        libnotify4 \
                        libxslt1.1 \
                        libevent-2.1-6 \
                        libgles2 \
                        libgl1 \
                        libegl1 \
                        libvpx5 \
                        libnss3 \
                        libxss1 \
                        libasound2 \
                        libdbus-glib-1-2 \
                        libxt6  
      - name: unit-tests
        run: npm test

  functional-tests:
    needs: unit-tests
    name: FTs - NodeJS ${{ matrix.node_version }} & ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: install browser dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libwoff1 \
                        libopus0 \
                        libwebp6 \
                        libwebpdemux2 \
                        libenchant1c2a \
                        libgudev-1.0-0 \
                        libsecret-1-0 \
                        libhyphen0 \
                        libgdk-pixbuf2.0-0 \
                        libegl1 \
                        libnotify4 \
                        libxslt1.1 \
                        libevent-2.1-6 \
                        libgles2 \
                        libgl1 \
                        libegl1 \
                        libvpx5 \
                        libnss3 \
                        libxss1 \
                        libasound2 \
                        libdbus-glib-1-2 \
                        libxt6      
      - name: functional-tests
        run: npm run test-functional

      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/reports/html-report

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-${{ matrix.os }}-${{ matrix.node_version }}
          path: test/functional-tests/logs

  functional-tests-headful:
    needs: unit-tests
    name: FT in linux-headful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install browser dependencies
        run: |
          sudo apt-get install -y libwoff1 \
                        libopus0 \
                        libwebp6 \
                        libwebpdemux2 \
                        libenchant1c2a \
                        libgudev-1.0-0 \
                        libsecret-1-0 \
                        libhyphen0 \
                        libgdk-pixbuf2.0-0 \
                        libegl1 \
                        libnotify4 \
                        libxslt1.1 \
                        libevent-2.1-6 \
                        libgles2 \
                        libgl1 \
                        libegl1 \
                        libvpx5 \
                        libnss3 \
                        libxss1 \
                        libasound2 \
                        libdbus-glib-1-2 \
                        libxt6      
      - name: install xvfb
        run: sudo apt install xvfb
      - name: functional-tests-headful
        env:
          headless: false
        run: xvfb-run npm run test-functional
      - name: Upload html report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-reports-linux-headful
          path: test/functional-tests/reports/html-report        
      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-linux-headful
          path: test/functional-tests/logs

